### ISSUE TITLE
Provider cron_d doesn't handle multiple command

### ISSUE THREAD

**Issue by jmauro** [chef-cookbooks/cron#50]
Hey everyone,

Apparently there is no way to specified multiple command line into the cron_d provider, do you think this is a wrong pattern? If not, could be possible then to specify a template file?

Regards,
JM

**Comment by jmauro** [comment]
OK my mistake it is possible:
https://github.com/opscode-cookbooks/cron/blob/master/providers/d.rb#L37

**Comment by marplesoft** [comment]
I didn't understand what the solution was - how does one specify multiple commands for one cron_d entry?

**Comment by alexderz** [comment]
You specify multiple commands the same way you would do a one-liner at the shell: Separate them by semi-colons or '&&' depending on your needs.

**Comment by marplesoft** [comment]
Right but then different commands can't have different schedules.

**Comment by jmauro** [comment]
This exactly my point and I don't wanna create 2 différents cron_d resource
for adding 2 commands linked to a single package.

**Comment by alexderz** [comment]
If you want two different schedules, then you must have two different cron entries. I know that in a cron.d file, you can have multiple entries, but I don't believe this provider supports that today. 

IMO, it's more reliable and simpler to force a different cron.d file for each schedule that try to parse the file and manage the entries within.

Maybe it would be an acceptable compromise to use a common prefix for the cron names so that they are easy to identify as belonging to the same thing.

**Comment by tas50** [comment]
Multiple commands with different schedules should really be done with 2 declarations.
